### ISSUE TITLE
Error of boost::posix_time

### ISSUE THREAD

**Issue by wystephen** [wvu-navLab/RobustGNSS#2]
`gtsam/gtsam/nonlinear/LevenbergMarquardtOptimizer.cpp:68:3: error: ‘startTime_’ was not declared in this scope
   startTime_ = boost::posix_time::microsec_clock::universal_time();
   ^
/home/steve/RobustGNSS/gtsam/gtsam/nonlinear/LevenbergMarquardtOptimizer.cpp: In member function ‘void gtsam::LevenbergMarquardtOptimizer::writeLogFile(double)’:
/home/steve/RobustGNSS/gtsam/gtsam/nonlinear/LevenbergMarquardtOptimizer.cpp:112:34: error: ‘startTime_’ was not declared in this scope
         << 1e-6 * (currentTime - startTime_).total_microseconds() << ","`
There are some error happenned when I was trying to compile the code in Ubutnu 16.04 and Ubuntu 18.04. 
Could you please give me some advice about the version of boost library you have installed in your system?

**Comment by watsonryan** [comment]
My desktop is running Ubuntu 16.04 with boost version 1.58.
